[package]
name = "swift-gen"
version = "0.1.0"
authors = ["mb <mb@nesium.com>"]
edition = "2021"

[dependencies]
parser = { path = "../parser" }
thiserror = { workspace = true }

[dev-dependencies]
dir-diff = { workspace = true }
tempdir = { workspace = true }