[package]
name = "xcode-color-assets"
version = "0.1.0"
authors = ["mb <mb@nesium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0"
clap = "2.33"
serde_json = "1.0"

[dev-dependencies]
insta = "0.10"