use super::data::*;
use super::renderer::{Renderer, RendererConfig};

pub struct ColorSetRenderer {}

impl Renderer for ColorSetRenderer {
  fn render_into(&self, ruleset: &RuleSet, d: &mut String, config: &RendererConfig) {
    d.push_str(
      "// This file is automatically generated. Do not edit, your changes will be erased.\n",
    );
    d.push_str("\n");
    d.push_str("import UIKit\n");
    d.push_str("\n");
    d.push_str("extension UIColor {\n");
    self.render_ruleset_into(ruleset, d, config);
    d.push_str("}\n");
    d.push_str("\n");
    d.push_str(
r#"private final class BundleToken {
  static let bundle: Bundle = {
    #if SWIFT_PACKAGE
    return Bundle.module
    #else
    return Bundle(for: BundleToken.self)
    #endif
  }()
}
"#
    );
  }
}

impl ColorSetRenderer {
  fn render_ruleset_into(&self, ruleset: &RuleSet, d: &mut String, config: &RendererConfig) {
    d.push_str(&format!(
      "{}{}enum {} {{\n",
      config.indent(ruleset.identifier.depth),
      config.access_level.to_string(),
      ruleset.identifier.short
    ));

    for item in &ruleset.items {
      match item {
        RuleSetItem::Declaration(decl) => self.render_declaration_into(decl, d, config),
        RuleSetItem::RuleSet(ruleset) => self.render_ruleset_into(ruleset, d, config),
      }
    }

    d.push_str(&format!("{}}}\n", config.indent(ruleset.identifier.depth)));
  }

  fn render_declaration_into(
    &self,
    declaration: &Declaration,
    d: &mut String,
    config: &RendererConfig,
  ) {
    d.push_str(&format!(
      "{}{}static let {} = UIColor(named: \"{}\", in: BundleToken.bundle, compatibleWith: nil)!\n",
      config.indent(declaration.identifier.depth),
      config.access_level.to_string(),
      declaration.identifier.short,
      declaration.identifier.full
    ))
  }
}
