// This file is automatically generated. Do not edit, your changes will be erased.

import UIKit

extension UIColor {
  public enum Custom {
    public static let LightContentSeparator = UIColor(named: "LightContentSeparator")!
    public enum NumericInput {
      public static let Background = UIColor(named: "NumericInputBackground")!
      public enum DoneKey {
        public static let Background = UIColor(named: "NumericInputDoneKeyBackground")!
        public static let Highlight = UIColor(named: "NumericInputDoneKeyHighlight")!
        public static let Shadow = UIColor(named: "NumericInputDoneKeyShadow")!
        public static let Text = UIColor(named: "NumericInputDoneKeyText")!
      }
      public enum NumericKey {
        public static let Background = UIColor(named: "NumericInputNumericKeyBackground")!
        public static let Highlight = UIColor(named: "NumericInputNumericKeyHighlight")!
        public static let Shadow = UIColor(named: "NumericInputNumericKeyShadow")!
        public static let Text = UIColor(named: "NumericInputNumericKeyText")!
      }
    }
    public enum Text {
      public static let Primary = UIColor(named: "TextPrimary")!
      public static let Secondary = UIColor(named: "TextSecondary")!
    }
  }
}
